language: python
python:
 - "2.7"
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libboost-all-dev
 - git clone --depth 1 https://github.com/JohnLangford/vowpal_wabbit.git /tmp/vw
 - cd /tmp/vw && sudo make install && cd -
install:
 - pip install -r requirements.txt
 - pip install flake8
script:
 - python -c 'import vwoptimize, doctest; doctest.testmod(vwoptimize)'
 - cd tests && python -m unittest discover -v && cd ..
 - flake8 --max-line-length=180 . --ignore=F403,F405
