matrix:
    include:
        - os: osx
          language: generic
language: python
python:
 - "2.7"
cache:
 pip: true
 directories:
   - bincache
before_install:
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then virtualenv venv -p python; fi
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source venv/bin/activate; fi
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then HOMEBREW_NO_AUTO_UPDATE=1 brew install vowpal-wabbit; fi
 - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then sudo apt-get install -qq libboost-all-dev; fi
 - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then sudo python tests/install_vw.py; fi
 - vw --version
install:
 - pip install -r requirements.txt
 - pip install flake8 shelldoctest
 - pip install hanziconv
script:
 - python -c 'import vwoptimize, doctest, sys; sys.exit(doctest.testmod(vwoptimize).failed)'
 - cd tests && python ./shell-doctest --verbose=2 test && cd ..
 - flake8 --max-line-length=300 --ignore E402 *.py tests/
