language: python
python:
 - "2.7"
cache:
 pip: true
 directories:
   - bincache
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libboost-all-dev
 - sudo python tests/install_vw.py
 - vw --version
install:
 - pip install -r requirements.txt
 - pip install flake8 shelldoctest
script:
 - python -c 'import vwoptimize, doctest; doctest.testmod(vwoptimize)'
 - cd tests && python ./shell-doctest --verbose=2 test && cd ..
 - flake8 --max-line-length=300 --ignore E402 .
